import { geoToGrid } from './worldDotMap';

export const journeyPoints = [
  {
    id: 'lebanon-home',
    city: 'Beirut',
    country: 'Lebanon',
    geo: { lon: 35.5, lat: 33.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Home base',
    month: null,
    type: 'home',
    description: 'Where it all started. Learned to code, built my first projects, and dreamed about what comes next.',
    professional: [
      { role: 'Coding Instructor', company: 'Geek Express' },
      { role: 'Software / Simulation Engineer', company: 'inmind.ai' }
    ],
  },
  {
    id: 'paris-2018',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2018',
    month: 9,
    type: 'travel',
    description: 'My first trip abroad. Disneyland Paris, Eiffel Tower, and the Louvre. The cliché, but I loved it.',
    professional: null,
  },
  {
    id: 'beirut-after-paris-2018',
    city: 'Beirut',
    country: 'Lebanon',
    geo: { lon: 35.5, lat: 33.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2018',
    month: 9,
    type: 'home',
    description: 'Back home.',
    professional: null,
  },
  {
    id: 'rome-2019',
    city: 'Rome',
    country: 'Italy',
    geo: { lon: 12.5, lat: 41.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2019',
    month: 8,
    type: 'travel',
    description: 'My second trip abroad. Colosseum, Trevi Fountain, and the Pantheon. I gained 5 kilos of gelato and pizza.',
    professional: null,
  },
  {
    id: 'venice-2019',
    city: 'Venice',
    country: 'Italy',
    geo: { lon: 12.3, lat: 45.4 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2019',
    month: 8,
    type: 'travel',
    description: 'Gondolas and getting lost in the best way. Taxi boats, hidden canals, and the best pizza I have ever had.',
    professional: null,
  },
  {
    id: 'florence-2019',
    city: 'Florence',
    country: 'Italy',
    geo: { lon: 11.25, lat: 43.8 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2019',
    month: 8,
    type: 'travel',
    description: 'Renaissance art and the best gelato. Such a perfect city for study-abroad students. (I was not tho.)',
    professional: null,
  },
  {
    id: 'beirut-after-italy',
    city: 'Beirut',
    country: 'Lebanon',
    geo: { lon: 35.5, lat: 33.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2019',
    month: 8,
    type: 'home',
    description: 'Back home.',
    professional: null,
  },
  {
    id: 'tokyo-2025',
    city: 'Tokyo',
    country: 'Japan',
    geo: { lon: 138.7, lat: 35.7 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Feb 2025',
    month: 2,
    type: 'travel',
    description: 'A trip I had been planning for years. Wandered through Tokyo: Shibuya, Akihabara, Shinjuku -- every neighborhood a different world.',
    professional: null,
  },
  {
    id: 'osaka-2025',
    city: 'Osaka',
    country: 'Japan',
    geo: { lon: 134.5, lat: 34.7 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Mar 2025',
    month: 3,
    type: 'travel',
    description: 'Street food capital. Had the best yakiniku of my life. Pretty bizarre place.',
    professional: null,
  },
  {
    id: 'kyoto-2025',
    city: 'Kyoto',
    country: 'Japan',
    geo: { lon: 134.8, lat: 35.0 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Mar 2025',
    month: 3,
    type: 'travel',
    description: 'Temples, bamboo forests, and the quietest streets I have ever walked. Too many stairs. Went to a 1000-year-old temple and a 1000-year-old restaurant.',
    professional: null,
  },
  {
    id: 'nara-2025',
    city: 'Nara',
    country: 'Japan',
    geo: { lon: 134.8, lat: 34.7 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Mar 2025',
    month: 3,
    type: 'travel',
    description: 'Deer everywhere. They bow for crackers. They also bite. Went to random anime shops.',
    professional: null,
  },
  {
    id: 'mtfuji-2025',
    city: 'Mt Fuji',
    country: 'Japan',
    geo: { lon: 137.7, lat: 35.4 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Feb 2025',
    month: 2,
    type: 'travel',
    description: 'Visible for the two days I was there. Biked around Lake Kawaguchiko. Went to a very fancy ryokan with a private onsen. Had a 7-course Wagyu dinner. Unlimited wine. Stood in awe of Mt Fuji.',
    professional: null,
  },
  {
    id: 'beirut-after-japan',
    city: 'Beirut',
    country: 'Lebanon',
    geo: { lon: 35.5, lat: 33.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Mar 2025',
    month: 3,
    type: 'home',
    description: 'Back home.',
    professional: null,
  },
  {
    id: 'warsaw-2025',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Jul 2025',
    month: 7,
    type: 'work',
    description: 'Six months in Warsaw for my Snowflake internship. Discovered pierogi, survived the cold, shipped production code, and used it as a base to explore Europe.',
    professional: [
      { role: 'SWE Intern', company: 'Snowflake' }
    ],
  },
  {
    id: 'prague-2025',
    city: 'Prague',
    country: 'Czech Republic',
    geo: { lon: 14.4, lat: 50.1 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2025',
    month: 8,
    type: 'travel',
    description: 'Weekend trip from Warsaw. Charles Bridge at sunrise, Old Town Square at night, and the best trdelník I never expected to love.',
    professional: null,
  },
  {
    id: 'warsaw-after-prague',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2025',
    month: 8,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'budapest-2025',
    city: 'Budapest',
    country: 'Hungary',
    geo: { lon: 19.0, lat: 47.5 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2025',
    month: 8,
    type: 'travel',
    description: 'Thermal baths and ruin bars. Budapest has an energy like no other city -- half historic grandeur, half underground cool.',
    professional: null,
  },
  {
    id: 'warsaw-after-budapest',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Aug 2025',
    month: 8,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'krakow-2025',
    city: 'Krakow',
    country: 'Poland',
    geo: { lon: 19.9, lat: 50.1 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'travel',
    description: 'Salt mines, pierogi (again), and some of the most powerful history I have ever walked through. Went mainly for an amusement park.',
    professional: null,
  },
  {
    id: 'warsaw-after-krakow',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'vienna-2025',
    city: 'Vienna',
    country: 'Austria',
    geo: { lon: 16.4, lat: 48.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'travel',
    description: 'Classical music floating through the streets, endless coffee culture, went to the Belvedere and a classical concert.',
    professional: null,
  },
  {
    id: 'warsaw-after-vienna',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'copenhagen-2025',
    city: 'Copenhagen',
    country: 'Denmark',
    geo: { lon: 12.57, lat: 55.68 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'travel',
    description: 'With my friends. Went to the Nyhavn and the big Copenhagen Zoo. Also a bizarre place.',
    professional: null,
  },
  {
    id: 'malmo-2025',
    city: 'Malmö',
    country: 'Sweden',
    geo: { lon: 13.0, lat: 55.6 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'travel',
    description: 'A 20 min trip from Copenhagen. My friends insisted.',
    professional: null,
  },
  {
    id: 'warsaw-after-scandinavia',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Sep 2025',
    month: 9,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'london-2025',
    city: 'London',
    country: 'United Kingdom',
    geo: { lon: -0.1, lat: 51.5 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Oct 2025',
    month: 10,
    type: 'travel',
    description: '3-day London visit. Museums, Notting Hill, Borough Market, St Paul’s Cathedral, and it was raining, yes. Loved it anyway. Probably the best city I have ever visited.',
    professional: null,
  },
  {
    id: 'warsaw-after-london',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Oct 2025',
    month: 10,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'paris-nov-2025',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Nov 2025',
    month: 11,
    type: 'travel',
    description: 'Second time to Paris. Autumn leaves, croissants, and a city that felt like it was waiting for me. (Spoiler alert: it was.)',
    professional: null,
  },
  {
    id: 'warsaw-after-paris',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Nov 2025',
    month: 10,
    type: 'work',
    description: 'Back to base.',
    professional: null,
  },
  {
    id: 'paris-dec-2025',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Dec 2025',
    month: 11,
    type: 'travel',
    description: 'Third time to Paris. A quick trip while doing my interviews, Christmas was starting.',
    professional: null,
  },
  {
    id: 'warsaw-return-2025',
    city: 'Warsaw',
    country: 'Poland',
    geo: { lon: 21.0, lat: 52.2 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Nov 2025',
    month: 11,
    type: 'work',
    description: 'Back to wrap up the internship. Last pierogi runs and goodbyes.',
    professional: null,
  },
  {
    id: 'paris-dec-2025',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Dec 2025',
    month: 12,
    type: 'travel',
    description: 'Paris in winter. Christmas markets, lights on the Champs-Élysées, and the decision to come back for good.',
    professional: null,
  },
  {
    id: 'strasbourg-2025',
    city: 'Strasbourg',
    country: 'France',
    geo: { lon: 7.75, lat: 48.58 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Dec 2025',
    month: 12,
    type: 'travel',
    description: 'Christmas markets as well, raclette and very good crêpes. A very nice Christmas.',
    professional: null,
  },
  {
    id: 'paris-after-strasbourg',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Dec 2025',
    month: 12,
    type: 'travel',
    description: 'Back to Paris, funemployment, and getting ready for a new year.',
    professional: null,
  },
  {
    id: 'lebanon-return',
    city: 'Beirut',
    country: 'Lebanon',
    geo: { lon: 35.5, lat: 33.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Dec 2025 — Jan 2026',
    month: 12,
    type: 'home',
    description: 'Back home for the holidays. Recharged with family, really good food, and a nice ski trip before the next chapter.',
    professional: null,
  },
  {
    id: 'paris-2026',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Feb 2026',
    month: 2,
    type: 'work',
    description: 'Now based in Paris, building the future of AI at Mistral AI. Croissants for breakfast, code all day, Seine walks at sunset.',
    professional: [
      { role: 'Software Engineer', company: 'Mistral AI' }
    ],
  },
  {
    id: 'london-apr-2026',
    city: 'London',
    country: 'United Kingdom',
    geo: { lon: -0.1, lat: 51.5 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Apr 2026',
    month: 4,
    type: 'travel',
    description: 'A quick trip to see family and experience London again. Loved it. Bought some really cool vinyls and Hirono merch.',
    professional: null,
  },
  {
    id: 'paris-apr-2026',
    city: 'Paris',
    country: 'France',
    geo: { lon: 2.35, lat: 48.9 },
    get coordinates() { return geoToGrid(this.geo.lon, this.geo.lat); },
    dateRange: 'Apr 2026 — Present',
    month: 4,
    type: 'current',
    description: 'Back in Paris. Building, exploring, living.',
    professional: null,
  }
];

export function getJourneyStats() {
  const cities = new Set(journeyPoints.map(p => p.city));
  const countries = new Set(journeyPoints.map(p => p.country));
  const continents = new Set();
  const continentMap = {
    'Lebanon': 'Asia', 'France': 'Europe', 'Italy': 'Europe',
    'Japan': 'Asia', 'Poland': 'Europe', 'Czech Republic': 'Europe',
    'Hungary': 'Europe', 'Austria': 'Europe', 'Denmark': 'Europe',
    'Sweden': 'Europe', 'United Kingdom': 'Europe',
  };
  journeyPoints.forEach(p => {
    if (continentMap[p.country]) continents.add(continentMap[p.country]);
  });
  return { cities: cities.size, countries: countries.size, continents: continents.size };
}

export function getSeasonalHue(month) {
  if (!month) return null;
  if (month >= 3 && month <= 5) return 140;
  if (month >= 6 && month <= 8) return 35;
  if (month >= 9 && month <= 11) return 25;
  return 210;
}
